import { latestCompletedUsTradingSession, sessionDateFromTimestamp } from "./market-calendar.js?v=8.0";

const FX_PRIMARY = "https://api.frankfurter.dev/v2/rate/USD/CNY";
const FX_BACKUP = "https://open.er-api.com/v6/latest/USD";
const YAHOO = "https://query1.finance.yahoo.com/v8/finance/chart/";
const NASDAQ = "https://api.nasdaq.com/api/quote/";
let marketEndpoint = "";
export const SNAPSHOT_PATH = "./data/market.json";
const SNAPSHOT_MIRROR = "https://raw.githubusercontent.com/dingdinglean/tangping-dividend-ding/main/data/market.json";
let snapshotPromise = null; let snapshotLoadedAt = 0;
const validDate = (v) => typeof v === "string" && /^\d{4}-\d{2}-\d{2}$/.test(v) && Number.isFinite(Date.parse(`${v}T00:00:00Z`));
const validPrice = (v) => Number.isFinite(Number(v)) && Number(v) > 0;

export function snapshotUrls(location = globalThis.location) { return location?.hostname === "dingdinglean.github.io" && location.pathname.startsWith("/tangping-dividend-ding/") ? [SNAPSHOT_PATH, SNAPSHOT_MIRROR] : [SNAPSHOT_PATH]; }
export function configureMarketEndpoint(value = "") { if (value !== marketEndpoint) { snapshotPromise = null; snapshotLoadedAt = 0; } if (!value || value === SNAPSHOT_PATH) { marketEndpoint = value; return; } const url = new URL(value); if (url.protocol !== "https:" || url.username || url.password || url.search || url.hash) throw new Error("共享服务请填写无参数的 HTTPS 地址"); marketEndpoint = url.href; }
async function fetchJson(url, timeoutMs = 18000) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetch(url, { signal: controller.signal, headers: { Accept: "application/json" }, cache: "no-store" }); if (!response.ok) throw new Error(response.status === 429 ? "行情请求额度已用完" : `HTTP ${response.status}`); return await response.json(); } catch (error) { if (error?.name === "AbortError") throw new Error("请求超时"); throw error; } finally { clearTimeout(timer); } }
async function readSnapshotCopy(url) { let cache; const key = globalThis.location ? new URL(url, globalThis.location.href).href : url; try { cache = await globalThis.caches?.open("tangping-market-snapshots-v2"); } catch {} try { const data = await fetchJson(url); if (data?.schemaVersion !== 2 || !data.symbols) throw new Error("invalid snapshot"); try { await cache?.put(key, new Response(JSON.stringify(data), { headers: { "Content-Type": "application/json" } })); } catch {} return data; } catch (error) { try { const cached = await cache?.match(key); if (cached) return await cached.json(); } catch {} throw error; } }
async function loadSnapshot() { if (!snapshotPromise || Date.now() - snapshotLoadedAt > 60000) { snapshotLoadedAt = Date.now(); snapshotPromise = Promise.allSettled(snapshotUrls().map(readSnapshotCopy)).then((items) => { const valid = items.filter((item) => item.status === "fulfilled" && item.value?.schemaVersion === 2).map((item) => item.value); if (!valid.length) throw new Error("暂时无法读取静态行情，请检查 Actions 或网络；已有行情仍保留"); return valid.sort((a, b) => Date.parse(b.generatedAt) - Date.parse(a.generatedAt))[0]; }).catch((error) => { snapshotPromise = null; throw error; }); } return snapshotPromise; }
export function parseSnapshot(snapshot, symbol, kind) { if (snapshot?.schemaVersion !== 2 || !snapshot.symbols) throw new Error("静态行情快照格式无效"); if (kind === "FX") { if (!validPrice(snapshot.fx?.rate) || !validDate(snapshot.fx?.fx_date)) throw new Error("USD/CNY 静态数据尚未生成"); return snapshot.fx; } const row = snapshot.symbols[symbol]; if (!row) throw new Error(`${symbol} 静态行情尚未生成`); const map = { PRICE: row.price, DIVIDENDS: row.dividends, DIVIDEND_RATE: row.dividend_rate }; if (!map[kind]) throw new Error(`${symbol} ${kind} 数据尚未生成`); return { ...map[kind], _status: kind === "PRICE" ? row.price_status : map[kind].status || "valid", _expectedDate: row.expected_price_date, _error: row.price_error || null }; }
function quoteFromRecord(record) { return { price: Number(record.price), tradingDay: record.price_date, priceDate: record.price_date, source: record.source, fetchedAt: record.fetched_at, refreshWarning: record._status === "valid" ? null : "快照数据日期落后于最近完成交易日", changePercent: 0 }; }
async function yahooPrice(symbol) { const url = new URL(`${YAHOO}${encodeURIComponent(symbol)}`); url.search = new URLSearchParams({ range: "10d", interval: "1d", includePrePost: "false" }).toString(); const data = await fetchJson(url); const result = data.chart?.result?.[0]; const rows = (result?.timestamp || []).map((stamp, index) => ({ price: Number(result?.indicators?.quote?.[0]?.close?.[index]), priceDate: sessionDateFromTimestamp(Number(stamp) * 1000) })).filter((row) => validPrice(row.price) && validDate(row.priceDate)).sort((a, b) => b.priceDate.localeCompare(a.priceDate)); if (!rows.length) throw new Error(`${symbol} 备用行情未返回有效收盘价`); return { ...rows[0], tradingDay: rows[0].priceDate, source: "Yahoo Finance Chart", fetchedAt: new Date().toISOString(), refreshWarning: null, changePercent: 0 }; }
async function nasdaqClose(symbol) { const url = new URL(`${NASDAQ}${encodeURIComponent(symbol)}/info`); url.search = new URLSearchParams({ assetclass: "etf" }).toString(); const quote = (await fetchJson(url)).data?.secondaryData || {}; const match = /(?:Closed at\s*)?([A-Z][a-z]{2})\s+(\d{1,2}),\s*(\d{4})/.exec(String(quote.lastTradeTimestamp || "")); const months = { Jan: "01", Feb: "02", Mar: "03", Apr: "04", May: "05", Jun: "06", Jul: "07", Aug: "08", Sep: "09", Oct: "10", Nov: "11", Dec: "12" }; const priceDate = match ? `${match[3]}-${months[match[1]]}-${match[2].padStart(2, "0")}` : ""; const price = Number(String(quote.lastSalePrice || "").replace(/[^0-9.]/g, "")); if (!validPrice(price) || !validDate(priceDate)) throw new Error(`${symbol} Nasdaq 未返回有效收盘价`); return { price, priceDate, tradingDay: priceDate, source: "Nasdaq official close", fetchedAt: new Date().toISOString(), refreshWarning: null, changePercent: 0 }; }
export async function fetchAlphaQuote(symbol) { const snapshot = await loadSnapshot(); const record = parseSnapshot(snapshot, symbol, "PRICE"); const expected = latestCompletedUsTradingSession().date; if (record.price_date === expected && record._status === "valid") return quoteFromRecord(record); try { const backup = await nasdaqClose(symbol); if (backup.priceDate === expected) return backup; } catch {} try { const backup = await yahooPrice(symbol); if (backup.priceDate === expected) return backup; } catch {} return quoteFromRecord({ ...record, _status: "stale" }); }
export async function fetchAlphaDividends(symbol) { const row = parseSnapshot(await loadSnapshot(), symbol, "DIVIDENDS"); const dividends = (row.data || []).map((item) => ({ exDate: item.ex_date, declarationDate: "", recordDate: "", paymentDate: item.payment_date || "", amount: Number(item.amount) })).filter((item) => validDate(item.exDate) && validPrice(item.amount)); if (!dividends.length) throw new Error(`${symbol} 未返回有效股息记录`); return { dividends, source: row.source, quality: "exact", fetchedAt: row.fetched_at, refreshWarning: null }; }
export async function fetchAlphaMonthlyAdjustedDividends() { throw new Error("静态快照未提供月度估算股息"); }
export async function fetchAlphaOverviewDividend(symbol) { const row = parseSnapshot(await loadSnapshot(), symbol, "DIVIDEND_RATE"); if (!validPrice(row.rate) || row.coverage === "insufficient") throw new Error(`${symbol} 股息历史不足 12 个月`); return { annualDividendPerShare: Number(row.annual_per_share || 0), dividendYield: Number(row.rate), dataDate: row.data_date || "", source: row.source, fetchedAt: row.fetched_at || null, quality: row.kind || "snapshot", yieldType: row.yield_type || row.kind || "snapshot", stale: row._status === "stale", refreshWarning: row._status === "stale" ? "股息率来源刷新失败，继续使用上次有效数据" : null, coverage: row.coverage || "complete" }; }
async function fxPrimary() { const row = await fetchJson(FX_PRIMARY); if (!validPrice(row.rate) || !validDate(row.date)) throw new Error("汇率数据格式异常"); return { rate: Number(row.rate), date: row.date, source: "Frankfurter", fetchedAt: new Date().toISOString() }; }
async function fxBackup() { const row = await fetchJson(FX_BACKUP); const date = sessionDateFromTimestamp(Number(row.time_last_update_unix || 0) * 1000) || new Date().toISOString().slice(0, 10); if (!validPrice(row.rates?.CNY)) throw new Error("汇率数据格式异常"); return { rate: Number(row.rates.CNY), date, source: "Open Exchange Rates", fetchedAt: new Date().toISOString() }; }
export async function fetchUsdCnyRate() { try { const row = parseSnapshot(await loadSnapshot(), "", "FX"); if (Date.now() - Date.parse(row.fetched_at) < 36 * 3600000 && row.status !== "stale") return { rate: Number(row.rate), date: row.fx_date, source: row.source, fetchedAt: row.fetched_at }; } catch {} try { return await fxPrimary(); } catch { return fxBackup(); } }
export const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
